apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcf-sa
automountServiceAccountToken: true
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcf-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - pods
  verbs: ["get", "list"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcf-rb
subjects:
- kind: ServiceAccount
  name: kcf-sa
roleRef:
  kind: Role
  name: kcf-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcf-clusterrole
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - pods
  verbs: ["get", "list"]
- nonResourceURLs: [ "/monitoring"]
  verbs: ["get"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcf-crb
subjects:
- kind: ServiceAccount
  name: kcf-sa
  namespace: carbon-footprint
roleRef:
  kind: ClusterRole
  name: kcf-clusterrole
  apiGroup: rbac.authorization.k8s.io
