apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: kcf-agent
  name: kcf-agent
  namespace: carbon-footprint
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kcf-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kcf-agent
    spec:
      containers:
      - image: quay.io/skhoury/kube-carbon-footprint:v0.0.1
        imagePullPolicy: Always
        name: kcf-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: kcf-sa
      terminationGracePeriodSeconds: 30


